# Site wide configuration

title:            "Attaining Vision"
locale: en_US
description:      "Developer notebook of Daniel Alberto Cañas."
#logo:             site-logo.png
disqus_shortname:
search:           true
# Change url to your domain. Leave localhost server or blank when working locally.
# You don't need to specify the protocol if you want it available on http and https. Example: //localhost:4000
url:         "//dacamo76.com"


# Jekyll configuration

permalink:  "/:categories/:year/:month/:day/:title/"
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: "1..6"
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "README.md", "LICENSE", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "vendor"]


# Site owner
owner:
  name:              "Daniel Alberto Cañas"
  avatar:            "http://www.gravatar.com/avatar/846bb87e41ead444942607d847fe46a7?s=200&d=mm"
  email:             daniel_76@yahoo.com
  disqus-shortname:
  twitter:           dacamo76
  facebook: #username
  github:            dacamo76
  stackexchange: http://stackoverflow.com/users/215199
  linkedin: danielcanas
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: 116829273000844440639
    analytics:
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
